from typing import List, Dict, Any, Optional

from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """
    Request model for the /chat endpoint.
    """
    user_message: str = Field(..., description="The natural language message from the user.")

class ChatResponse(BaseModel):
    """
    Response model for the /chat endpoint.
    """
    agent_response: str = Field(..., description="The natural language response generated by the agent.")

# --- API Endpoint Definition (Conceptual) ---
# The /chat FastAPI endpoint would have a signature similar to this:
#
# @app.post("/chat", response_model=ChatResponse)
# async def chat_with_agent(request: ChatRequest):
#     """
#     Handles chat interactions with the Gemini-powered RAG agent.
#     """
#     # Implementation details in backend/api.py and backend/agent.py
#     pass
